### PR TITLE
[BUGFIX] Fix the ability to change an option dynamically

### LINKED ISSUE #9: Disabled option doesn't work correctly.
In our case when the disabled option is a dynamic value, the option works correctly the first time but after changing the value to false, the first level of nested sortable works incorrectly.

`<SortableJs
    class="sortable"
    @options={{hash animation=150 fallbackOnBody=true swapThreshold=0.65 group=group dragClass="sortable-drag" disabled=disabledSortable }}
    @onEnd={{action onEnd}}
    @onChoose={{action "onChoose"}}
    @onUnchoose={{action onUnchoose}}
    @onChange={{action "onChange"}}
>

    <div class="tree-sortable>
        {{#if sortedTreeData.length}}
            {{#each sortedTreeData as |treeItem|}}
                <TreeItem
                    @treeItem={{treeItem}}
                    @onEnd={{action onEnd}}
                    @onChoose={{action onChoose}}
                    @onUnchoose={{action onUnchoose}} />
            {{/each}}
        {{/if}}
    </div>

</SortableJs>`

### PR DESCRIPTION
**Pull request by lvegerano**
Fixes #9

### CODE REVIEW

File: addon/components/sortable-js.js [hunk 1]
```diff
@@ -30,6 +31,17 @@ export default Component.extend({
     'onFilter',
   ]),
 
+  didReceiveAttrs: diffAttrs('options', function(changedAttrs, ...args) {
+    this._super(...args);
+    if(changedAttrs && changedAttrs.options) {
+      const options = changedAttrs.options.pop();
+      for (let [key, value] of Object.entries(options)) {
+        console.log('setting options', key, value);
```
Comment (arthay) [inline addon/components/sortable-js.js]: Please remove console.log.
Thank You.
